### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by OConnorsRule** [Tschipcraft/dynamiclights#41] opened 2024-06-20 19:28 UTC
### Additional context

i am woondering 1.21 support will be added

**Comment by nutyus** [comment] 2024-06-21 02:10
it will be, but idk if there is ETA?

**Comment by Tschipcraft** [comment] 2024-06-21 14:14
I will start working on the update in approx. 2 weeks after my exams. Thanks for your patience!
Duplicate of #29

**Comment by Tschipcraft** [comment] 2024-06-21 14:17
Duplicate of #29

**Closed** 2024-07-10 22:07 UTC
Labels: duplicate, enhancement
