### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by DarkAsgard124** [Tschipcraft/dynamiclights#42] opened 2024-06-23 12:54 UTC
### Additional context

I know this is probably one of 200 other requests for 1.21 support. But I am making a Realm map, torches emitting light while being held is one of most important systems in the map. Is there any way to enable the datapack to work with 1.21, I don't need it to work with new blocks that have been added in 1.21 , just old regular ones from 1.20.6 but make it work with 1.21 . Thank you in advance.

**Comment by DarkAsgard124** [comment] 2024-06-23 12:56
I really need it as soon as possible, but i cant find any other person on whole internet that does that you do. If you arent able to do it right now, can you explain the process of updating it to version 1.21 so i can try to do it if it isnt too complicated.

**Comment by Tschipcraft** [comment] 2024-06-23 15:54
1.21 introduced a bunch of directory renames. If you don't care about enchantment detection and/or backwards compatibility, that's the only thing you need to worry about.
Download the latest release, unzip it and rename the folders

- `functions` to `function`
- `predicates` to `predicate`
- `tags/blocks` to `tags/block`
- `tags/items` to `tags/item`
- `tags/entity_types` to `tags/entity_type`
- `tags/functions` to `tags/function`

in `data/dynamiclights`, `data/minecraft`, `data/tschipcraft`, `overlay_33/data/dynamiclights` and `overlay_35/data/dynamiclights`. This should be enough to get Dynamic Lights running in 1.21. You might need to disable light emitting from enchantments in the settings though.
Do also keep the license in mind and provide credit when releasing the map.

**Comment by BrailleBennett** [comment] 2024-06-23 16:28
Does this work around also work for the datapack or just the mod since enchantment detection isn't configurable on the pack?

**Comment by DarkAsgard124** [comment] 2024-06-24 12:43
I have tried it, the game doesnt even recognize it as a datapack, when i put old one, it appears but red and game says its made for older version, when i put in the one that i have edited, nothing appears

**Comment by Tschipcraft** [comment] 2024-06-24 15:10
> Does this work around also work for the datapack or just the mod since enchantment detection isn't configurable on the pack?

This workaround is tailored for the data pack version, all settings from the mod version are also available there (`/function dynamiclights:settings`)

**Comment by Tschipcraft** [comment] 2024-06-24 15:14
> I have tried it, the game doesnt even recognize it as a datapack, when i put old one, it appears but red and game says its made for older version, when i put in the one that i have edited, nothing appears

You may have rezipped the edited version incorrectly. Make sure that the data folder and pack.mcmeta are in the first level (dynamiclights-edited.zip ⇾ data, overlay_..., pack.mcmeta, ...)
If that doesn't solve the problem, attach your most recent Minecraft log, so I can take a look.

**Comment by DarkAsgard124** [comment] 2024-06-24 18:11
Fixed it, i made it .rar file instead of .zip
Any way to disable the "Minecraft version 1.21 or above detected". I cant send the map for reviewing with any error messages, bugs and other stuff like thet.

**Comment by Tschipcraft** [comment] 2024-06-24 18:43
Yes, run the command `/scoreboard players set $global tvc_ignore 1`. Make sure to not reset the scoreboards before publishing the map.

**Comment by Tschipcraft** [comment] 2024-07-05 11:05
Duplicate of #29

**Closed** 2024-07-10 22:07 UTC
Labels: bug, duplicate
