### ISSUE TITLE
Massive problems with Dynamic Lights

### ISSUE THREAD

**Issue by XavierBit** [Tschipcraft/dynamiclights#10] opened 2023-09-03 01:58 UTC
### Describe the bug

There are actually three bugs which we had to track down. After cloning the server to a local environment, it took us days to find that Dynamic Light not just messes with TNT but also with Skulk sensors.

Please don't understand this bug report as a rant, more as a possibility to make this data pack even better and for others to find a solution to a problem, which seemingly has nothing to do with Dynamic Lights.

Our environment:
We have set up a Fabric moded server using Minecraft 1.20.1 with Fabric Loader 0.14.21 and the following mods:
[08.27.23_Memory_In-Between_Modlist.txt](https://github.com/Tschipcraft/dynamiclights/files/12505016/08.27.23_Memory_In-Between_Modlist.txt)

We are having problems with TNT blocks as it isn't possible to ignite them with a flame bow:
Flame bow 1st try:
https://www.youtube.com/watch?v=LOK2TG4cd8U

Flame bow 2nd try:
https://www.youtube.com/watch?v=VvVGtd4p1-E

But it works using Redstone

https://www.youtube.com/watch?v=Tqk7KwzZAfA

We do have problems with TNT dupers as well, which sometimes work, but fail at about 80%: 
![image](https://github.com/Tschipcraft/dynamiclights/assets/95314871/fef23a8d-e699-4977-9996-227c25091e8d)

It's not consistent as this time, when I filmed it, most of the dupers worked correctly but some failed
https://www.youtube.com/watch?v=anO7eCW091o

As well Skulk sensors are detecting players on wool blocks:
https://www.youtube.com/watch?v=rIJYdKrTsjE

We searched high and low in every config and setting, expecting that we messed up with player rights or TNT explosions.
Somehow we stumbled over an issue here at this page and tried it out. Removing Dynamic Lights solved all problems mentioned above!

### Steps to reproduce

1. Try to ignite TNT with flame bow.
2. Dupe TNT 
3. Move towards a Skulk Sensor on wool blocks

### Expected behavior

1. TNT explodes, breaking blocks and ignites next TNT
2. TNT shouldn't appear on two places at the same time
3. Skulk sensor should not detect player

**Comment by Tschipcraft** [comment] 2023-09-03 09:32
Sorry for that bug hunt, vanilla light blocks block explosion damage for some reason.
I only work on my data packs in my free time, so I don't have much time actually play testing them to their fullest extent, so I only noticed the problem via Redstone... That's why that works lol

The TNT dupers probably break due to the block updates caused by placing the light block.

The problem with the sculk sensors has already been resolved, but the fix is currently only in the GitHub repo and not yet distributed to GitHub releases, Modrinth, etc. (see #8)

Thank you for the bug report! These issues will be fixed.

**Comment by XavierBit** [comment] 2023-09-03 14:44
Hi Tschipcraft, 

We understand that the TNT problem is hard to figure out, that's why I made this extended post so others don't have to do the leg work we have done. It was actually this issue #8 which got us on the right path. Thankfully my way to scour Github is to always look at the 'solved' issues as well.

Minecraft lives from data pack and mod makers alike. We are grateful for your contribution and for your dedicated work and we will have an eye on your updates so we can come back to this when those problems are resolved.

**Comment by Tschipcraft** [comment] 2023-09-03 17:16
Thank you <3

**Comment by Tschipcraft** [comment] 2023-09-03 17:47
I've now implemented a fix, that resolves at least all the mentioned TNT bugs.
I've compiled a v1.7-beta version for you to try out:
[dynamiclights-v1.7-beta-mc1.17x-1.20x-datapack.zip](https://github.com/Tschipcraft/dynamiclights/files/12506722/dynamiclights-v1.7-beta-mc1.17x-1.20x-datapack.zip)

**Closed** 2023-09-04 20:48 UTC
Labels: bug
